### PR TITLE
Fix 200

### LINKED ISSUE #200: nrf_to_nrf.h expected for any nRF5x board in CI
Since nrf_to_nrf isn't a named lib dependency, the lib is not installed in CI and [fails on the Arduino 33 Nano BLE](https://github.com/nRF24/RF24Network/actions/runs/3826975905/jobs/6511195829#step:3:62) board.

### Solution
Just make nrf_to_nrf a dependency and install it CI.

### PR DESCRIPTION
**Pull request by 2bndy5**
A follow up to https://github.com/nRF24/RF24Network/commit/7a7a8543443eeb1352d9bb99264d0e8c76baa624 that resolves #200 and get the CI passing again.

### CODE REVIEW

File: RF24Network.cpp [hunk 1]
```diff
@@ -447,59 +447,59 @@ uint8_t RF24Network::enqueue(RF24NetworkHeader* header)
             IF_SERIAL_DEBUG_FRAGMENTATION_L2(for (int i = 0; i < frag_queue.message_size; i++) { printf_P(PSTR("%02x"), frag_queue.message_buffer[i]); });
             return true;
         }
-        else // NETWORK_MORE_FRAGMENTS
-            if (header->type == NETWORK_LAST_FRAGMENT || header->type == NETWORK_MORE_FRAGMENTS) {
+        // else if not first fragment
+        else if (header->type == NETWORK_LAST_FRAGMENT || header->type == NETWORK_MORE_FRAGMENTS) {
```
Comment (2bndy5) [inline RF24Network.cpp:451]: clang-fomat had a problem here. I must admit it was a little hard to read myself, so I moved around the comment and let clang-format fix the indentation.

**Review by TMRh20 — APPROVED** [review]
